import Head from 'next/head'
import styles from '/styles/Home.module.css'
import Footer from '../components/FooterComponent/footer'
import Nav from '../components/Nav/Nav'
import purpleBg from '../public/PurpleBg.png'
import ValueProp from '../components/ValuePropSection/ValueProp'
import Benefits from '../components/BenefitsSection/Benefits'
import GetStartedBtn from '../components/Buttons/GetStartedBtn'

export default function Home() {
  return (
    <>
      <Head>
        <title>InnerSight Customer Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link
          href="https://fonts.googleapis.com/css2?family=Lexend:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        /> */}
      </Head>
      <div className={styles.fullWidthContent}>
        <Nav />
        <ValueProp />
      </div>
      <main className={styles.main}>
        <Benefits />
        <div className={styles.ctaBottom}>
          <h2>Ready to Write?</h2>
          <GetStartedBtn />
        </div>
      </main>
      <Footer />
    </>
  )
}
