import Head from 'next/head'
import styles from '/styles/Privacy.module.css'
import Footer from '../components/FooterComponent/footer'
import Nav from '../components/Nav/Nav'
import PolicyData from '../data/PolicyData'
import { useState } from 'react'

export default function Privacy() {
    const [data, setData] = useState(PolicyData.questions);

    return (
        <>
            <Head>
                <title>InnerSight Privacy Policy</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                {/* <link
                    href="https://fonts.googleapis.com/css2?family=Lexend:wght@300;400;500;600;700&display=swap"
                    rel="stylesheet"
                /> */}
            </Head>
            <div className={styles.fullWidthContent}>
                <Nav />
            </div>
            <main className={styles.main}>
                <h1>Privacy Policy</h1>
                    {data && data.map((i, index) => (
                        i.page === "Privacy Policy" ?
                            <div
                                className={styles.questionContainer}
                                key={index}>
                                <div className={styles.btnTextLrg}>
                                    <h2>{index + 1}. {i.header}</h2>
                                </div>
                                {
                                    i.content.personalInfo ?
                                        <>
                                            <div className={styles.bodyCopy}>
                                                <div className={styles.btnTextLrg}><h3>{i.subtitle1}:</h3></div> <p>{i.content.personalInfo}</p>
                                            </div>
                                            <div className={styles.bodyCopy}>
                                                <div className={styles.btnTextLrg}><h3>{i.subtitle2}:</h3></div> <p>{i.content.journalEntries}</p>
                                            </div>
                                        </>
                                        :
                                        <div className={styles.bodyCopy}>
                                            <p>{i.content}</p>
                                        </div>
                                }
                            </div>
                            :
                            ""
                    ))}
            </main>
            <Footer />
        </>
    )
}
